import { WorkflowTemplate } from "@/types/workflow";

export const DEFAULT_WORKFLOWS: WorkflowTemplate[] = [
  {
    id: "support-triage",
    name: "Customer Support & Inquiry Triage",
    description: "Evaluates inbound customer queries, routing technical and urgent billing issues to support, and product inquiries to sales.",
    inputExample: "Hello! My API subscription was charged twice yesterday and I cannot access my production dashboard. Please assist urgently.",
    nodes: [
      {
        id: "start-1",
        type: "startNode",
        position: { x: 50, y: 180 },
        data: { label: "Inbound Message Stream", inputKey: "customer_message" },
      },
      {
        id: "decision-1",
        type: "decisionNode",
        position: { x: 300, y: 150 },
        data: {
          label: "Support vs Sales Check",
          prompt: "Is this message asking for technical support, bug resolution, or account troubleshooting?",
          description: "Distinguishes technical support from new sales opportunities.",
        },
      },
      {
        id: "decision-2",
        type: "decisionNode",
        position: { x: 600, y: 60 },
        data: {
          label: "Urgency & Billing Triage",
          prompt: "Does this customer request involve payments, billing errors, or critical downtime needing urgent priority?",
          description: "Evaluates priority level for SLA dispatch.",
        },
      },
      {
        id: "action-urgent",
        type: "actionNode",
        position: { x: 920, y: 30 },
        data: { label: "Dispatch to Priority Tier-2 Support", actionType: "escalate" },
      },
      {
        id: "action-standard",
        type: "actionNode",
        position: { x: 920, y: 150 },
        data: { label: "Assign to Standard Helpdesk Queue", actionType: "assign_queue" },
      },
      {
        id: "action-sales",
        type: "actionNode",
        position: { x: 600, y: 320 },
        data: { label: "Route to Sales & Account Exec", actionType: "sales_lead" },
      },
    ],
    edges: [
      {
        id: "e-start-d1",
        source: "start-1",
        target: "decision-1",
        animated: true,
      },
      {
        id: "e-d1-yes",
        source: "decision-1",
        target: "decision-2",
        sourceHandle: "yes",
        label: "YES (Support)",
        data: { condition: "YES" },
        style: { stroke: "#10b981", strokeWidth: 2 },
      },
      {
        id: "e-d1-no",
        source: "decision-1",
        target: "action-sales",
        sourceHandle: "no",
        label: "NO (Sales)",
        data: { condition: "NO" },
        style: { stroke: "#ef4444", strokeWidth: 2 },
      },
      {
        id: "e-d2-yes",
        source: "decision-2",
        target: "action-urgent",
        sourceHandle: "yes",
        label: "YES (Urgent)",
        data: { condition: "YES" },
        style: { stroke: "#10b981", strokeWidth: 2 },
      },
      {
        id: "e-d2-no",
        source: "decision-2",
        target: "action-standard",
        sourceHandle: "no",
        label: "NO (Standard)",
        data: { condition: "NO" },
        style: { stroke: "#ef4444", strokeWidth: 2 },
      },
    ],
  },
  {
    id: "content-moderation",
    name: "Automated Content Moderation Pipeline",
    description: "Evaluates user submitted posts for toxic content, hate speech, and spam before publication.",
    inputExample: "Get rich quick with guaranteed 500% weekly returns! Visit http://free-crypto-giveaway.fake today!",
    nodes: [
      {
        id: "start-mod",
        type: "startNode",
        position: { x: 50, y: 160 },
        data: { label: "Incoming User Post", inputKey: "post_text" },
      },
      {
        id: "decision-toxic",
        type: "decisionNode",
        position: { x: 300, y: 130 },
        data: {
          label: "Toxicity & Abuse Check",
          prompt: "Does this submission contain hate speech, harassment, profanity, or toxic insults?",
          description: "Filters violation of safety policy.",
        },
      },
      {
        id: "action-block",
        type: "actionNode",
        position: { x: 620, y: 30 },
        data: { label: "Reject & Flag User Account", actionType: "reject" },
      },
      {
        id: "decision-spam",
        type: "decisionNode",
        position: { x: 620, y: 220 },
        data: {
          label: "Promotional Spam Check",
          prompt: "Is this submission unauthorized commercial advertising, scam, phishing, or bulk spam?",
          description: "Detects spam bot links and scams.",
        },
      },
      {
        id: "action-quarantine",
        type: "actionNode",
        position: { x: 920, y: 160 },
        data: { label: "Quarantine for Manual Moderator Review", actionType: "review" },
      },
      {
        id: "action-publish",
        type: "actionNode",
        position: { x: 920, y: 300 },
        data: { label: "Auto-Approve & Publish to Feed", actionType: "publish" },
      },
    ],
    edges: [
      {
        id: "e-mod-start",
        source: "start-mod",
        target: "decision-toxic",
        animated: true,
      },
      {
        id: "e-toxic-yes",
        source: "decision-toxic",
        target: "action-block",
        sourceHandle: "yes",
        label: "YES (Toxic)",
        data: { condition: "YES" },
        style: { stroke: "#ef4444", strokeWidth: 2 },
      },
      {
        id: "e-toxic-no",
        source: "decision-toxic",
        target: "decision-spam",
        sourceHandle: "no",
        label: "NO (Clean)",
        data: { condition: "NO" },
        style: { stroke: "#10b981", strokeWidth: 2 },
      },
      {
        id: "e-spam-yes",
        source: "decision-spam",
        target: "action-quarantine",
        sourceHandle: "yes",
        label: "YES (Spam)",
        data: { condition: "YES" },
        style: { stroke: "#f59e0b", strokeWidth: 2 },
      },
      {
        id: "e-spam-no",
        source: "decision-spam",
        target: "action-publish",
        sourceHandle: "no",
        label: "NO (Organic)",
        data: { condition: "NO" },
        style: { stroke: "#10b981", strokeWidth: 2 },
      },
    ],
  },
];
